import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Powered Text Processing Interface",
  description: "Generated by create next app",
  icons:{
    icon:"/IMessage_logo.ico", 
  } 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <----- Translator Token --------> */}
        <meta
          httpEquiv="origin-trial"
          content={process.env.NEXT_PUBLIC_ORIGIN_TRIAL_TOKEN_TRANSLATOR}
        />
        {/* <----- Language Detector Token ------> */}
        <meta
          httpEquiv="origin-trial"
          content={process.env.NEXT_PUBLIC_ORIGIN_TRIAL_TOKEN_LANGAUAGE_DETECTOR}
        />
        {/* <----- Summarization Token ------> */}
        <meta
          httpEquiv="origin-trial"
          content={process.env.NEXT_PUBLIC_ORIGIN_TRIAL_TOKEN_SUMMARIZATION}
        />
        <link rel="icon" href="/IMessage_logo.ico"/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
        {children}
      </body>
    </html>
  );
}
